markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Minimal Blog
tagline:          'I like KISS. By KISS I means "keep it simple and stupid". '
baseurl:          /

author:
  name:           Long

paginate:         5
recent-num:       5
article_num:      5
